on:
  workflow_call:
    inputs:
      release:
        description: name of release to push on docker registry
        type: string
        required: true
        default: v0.0.1

name: push-docker-image

jobs:
  push-docker-image:
    name: Build Docker image and push to registry
    runs-on: ubuntu-22.04
    steps:
      - name: debug
        run: |
          echo inputs.release = ${{ inputs.release }}

      - name: release version only numbers
        id: release-version
        run: |
          echo "${{ inputs.release }}" | sed 's|^[a-zA-Z]\+|RELEASE_VERSION=|' >> $GITHUB_OUTPUT

      - name: Set env ARTIFACT_PREFIX
        run: |
          echo ARTIFACT_PREFIX=${{ github.event.repository.name }}-${{ steps.release-version.outputs.RELEASE_VERSION }} >> $GITHUB_ENV

      - name: Download release asset amd64
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ inputs.release }}
          file: ${{ env.ARTIFACT_PREFIX }}.tgz
          token: ${{ secrets.GITHUB_TOKEN }}

      #- name: Download release asset arm64
      #  uses: dsaltares/fetch-gh-release-asset@master
      #  with:
      #    version: tags/${{ inputs.release }}
      #    file: ${{ env.ARTIFACT_PREFIX }}-arm64.tar.gz
      #    token: ${{ secrets.GITHUB_TOKEN }}

      - name: Unpack archive amd64
        run: |
          tar -zxf ${{ env.ARTIFACT_PREFIX }}.tgz
          rm -f ${{ env.ARTIFACT_PREFIX }}.tgz
          mv ${{ github.event.repository.name }} ${{ github.event.repository.name }}-amd64

      #- name: Unpack archive arm64
      #  run: |
      #    tar -zxf ${{ env.ARTIFACT_PREFIX }}-arm64.tar.gz
      #    rm -f ${{ env.ARTIFACT_PREFIX }}-arm64.tar.gz
      #    mv grpc-server grpc-server-arm64

      - name: Generate Dockerfile
        run: |
          cat <<EOF > Dockerfile
          # syntax=docker/dockerfile:1
          FROM alpine
          ARG TARGETARCH
          COPY ${{ github.event.repository.name }}-\$TARGETARCH ${{ github.event.repository.name }}
          EXPOSE 443
          EXPOSE 8000
          CMD ["./${{ github.event.repository.name }} -c /etc/${{ github.event.repository.name }}/config.yml"]
          EOF

      - name: Debug
        run: pwd; cat Dockerfile;  ls -R

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to registry
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          #platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ inputs.release }}
