on:
  workflow_dispatch:
    inputs:
      release:
        description: name of release to push on docker registry
        required: true
        default: v0.0.1

name: push-docker-image-manual

jobs:
  push-docker-image-manual:
    uses: anyproto/any-sync-node/.github/workflows/push-docker-image-reusable.yml@main
    with:
      release: ${{ github.event.inputs.release }}
      dockerfile-run: apt-get update && apt-get install -y ca-certificates
      dockerfile-cmd: /bin/any-sync-filenode -c /etc/any-sync-filenode/config.yml
