on:
  release:
    types: [published]

name: push-docker-image-release

jobs:
  push-docker-image-release:
    uses: ./.github/workflows/push-docker-image-reusable.yml
    with:
      release: ${{ github.event.release.tag_name }}
