name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions: write-all

jobs:
  release-reusable:
    uses: anyproto/shared-actions/.github/workflows/release-go-daemons-reusable.yml@v1
    secrets: inherit # pass all secrets
    with:
      start_redis: true
      dockerfile-run: apt-get update && apt-get install -y ca-certificates
      dockerfile-cmd: '["/bin/any-sync-filenode", "-c", "/etc/any-sync-filenode/config.yml"]'
